### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by camdenbrown-zz** [josa42/atom-blame#15]

**Comment by SlimeQ** [comment]
TypeError: Cannot read property 'add' of null
    at /home/quincy/.atom/packages/blame/lib/blame-gutter-view.js:275:25
    at /home/quincy/.atom/packages/blame/lib/utils/get-commit.js:51:5
    at /home/quincy/.atom/packages/blame/lib/utils/get-commit.js:29:5
    at /home/quincy/.atom/packages/blame/node_modules/git-wrapper/git.js:34:5
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
