### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by SlimeQ** [josa42/atom-blame#19]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Ubuntu 14.04.3
**Thrown From**: [blame](https://github.com/josa42/atom-blame) package, v0.9.1
### Stack Trace

Uncaught TypeError: Cannot read property 'add' of null

```
At /home/quincy/.atom/packages/blame/lib/blame-gutter-view.js:275

TypeError: Cannot read property 'add' of null
    at /home/quincy/.atom/packages/blame/lib/blame-gutter-view.js:275:25
    at /home/quincy/.atom/packages/blame/lib/utils/get-commit.js:51:5
    at /home/quincy/.atom/packages/blame/lib/utils/get-commit.js:29:5
    at /home/quincy/.atom/packages/blame/node_modules/git-wrapper/git.js:34:5
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -5:35 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -5:32.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:45.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -3:43.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:23.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:20 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 blame:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      "*.class"
    ],
    "packagesWithKeymapsDisabled": [
      "bracket-matcher"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "blame": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.4
atom-material-syntax, v0.3.0
atom-material-ui, v0.8.1
autocomplete-java, v0.12.4
autocomplete-oracle, v0.3.0
blame, v0.9.1
color-tabs, v0.1.8
docblockr, v0.7.3
git-plus, v5.12.1
java-importer, v1.4.1
language-babel, v2.14.1
language-docker, v1.1.6
language-groovy, v0.5.0
language-salesforce, v0.6.0
linter, v1.11.3
linter-docker, v0.1.2
linter-javac, v1.5.0
minimap, v4.19.0
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by josa42** [comment]
Can you give me more details on how to reproduce this?

**Comment by jakubhruby** [comment]
I have the same error after update to 0.10.0 from 0.9.0 - steps:
1. Open a file
2. Do blame:toggle
3. error appears

Edit:
reinstalling blame package helped

**Comment by vith** [comment]
This happens if you close the blame gutter while the blame info is still loading. Have to be quick, and maybe on a large repository.

**Comment by lucascosti** [comment]
Yep, I had this happen on a large file after I accidentally toggled blame on and toggled it back off before it finished loading.
