### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by gggritso** [josa42/atom-blame#25]
1. Open Atom
2. Toggle blame either by right-clicking, or using the command pane

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [blame](https://github.com/josa42/atom-blame) package, v0.10.0
### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/george.gritsouk/.atom/packages/blame/node_modules/blamer/src/vcs/git.js:11

TypeError: Cannot read property '1' of null
    at convertStringToObject (/Users/george.gritsouk/.atom/packages/blame/node_modules/blamer/src/vcs/git.js:11:23)
    at /Users/george.gritsouk/.atom/packages/blame/node_modules/blamer/src/vcs/git.js:38:20
    at Array.forEach (native)
    at /Users/george.gritsouk/.atom/packages/blame/node_modules/blamer/src/vcs/git.js:36:15
    at ChildProcess.exithandler (child_process.js:216:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -0:01.4.0 blame:toggle (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "html": [
        "tpl.php",
        "tmpl.php",
        "tmpl"
      ],
      "php": [
        "module"
      ]
    },
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "background-tips",
      "symbols-view",
      "deprecation-cop",
      "release-notes",
      "archive-view",
      "autocomplete-atom-api",
      "autoflow",
      "encoding-selector",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-toml",
      "link",
      "markdown-preview",
      "open-on-github",
      "package-generator",
      "livestyle-atom",
      "line-ending-selector",
      "bookmarks"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "build/*"
    ],
    "packagesWithKeymapsDisabled": [
      "git-diff"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.4
atom-ctags, v4.5.2
atom-ternjs, v0.14.1
autocomplete-paths, v1.0.2
blame, v0.10.0
cursor-history, v0.5.9
emmet, v2.4.3
highlight-selected, v0.11.2
language-fish-shell, v1.0.4
language-haml, v0.24.0
linter, v1.11.4
linter-eslint, v7.2.2
linter-haml, v1.2.0
linter-htmlhint, v1.1.4
linter-less, v2.5.0
minimap, v4.24.3
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
pretty-json, v1.4.0
project-manager, v2.9.7
relative-numbers, v0.5.1
vim-mode, v0.65.1
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by josa42** [comment]
I cannot reproduce this. Please add more info if it still occurs.
