### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by qmichalet** [josa42/atom-blame#51]
1. Modify a file
2. Save modifications

Randomly throws an error

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [blame](https://github.com/josa42/atom-blame) package 1.1.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:519139)
    at TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:27540)
    at BlameGutterView.addMarker (/packages/blame/lib/blame-gutter-view.js:177:17)
    at /packages/blame/lib/blame-gutter-view.js:115:14
    at Array.forEach (<anonymous>)
    at /packages/blame/lib/blame-gutter-view.js:100:27
    at /packages/blame/lib/provider/git/get-blame.js:43:7)
    at DestroyableTransform.emit (events.js:187:15)
    at endReadableNT (/packages/blame/node_modules/split-transform-stream/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -0:09.2.0 core:move-to-top (input.hidden-input)
     -0:07.1.0 editor:newline (input.hidden-input)
     -0:07.1.0 core:paste (input.hidden-input)
     -0:06.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
auto-detect-indentation 1.3.0 
blame 1.1.0 
busy-signal 2.0.1 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.35 
ide-ruby 0.4.0 
intentions 1.1.5 
linter 2.3.1 
linter-eslint 8.5.5 
linter-sass-lint 1.9.0 
linter-ui-default 1.8.0 
minimap 4.29.9 
npm-install 4.0.4 
react 0.18.0 
react-es6-snippets 0.3.0 
react-snippets 1.1.3 
```

**Comment by payneWeave** [comment]
Is there any kind of work around on this one?
